modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "LGPLv3"

[[mods]]
modId = "vivecraft"
version = "${version}"
displayName = "Vivecraft"
logoFile="vivecraft_icon.png"
authors = "fayer3, Ferri_Arnus, IMS, jrbudda, minecraft player"
displayTest="IGNORE_SERVER_VERSION"
description = '''
The VR mod for any loader!
'''
#logoFile = ""

[[dependencies.vivecraft]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vivecraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"
